### ISSUE TITLE
Change schedule's "Location" open comment box to drop-down menu

### ISSUE THREAD

**Issue by dzhlobo** [birs-math/workshops#3]
<img width="1267" alt="Screenshot 2023-01-09 at 12 29 16" src="https://user-images.githubusercontent.com/800337/211298424-88221ef2-e1c7-4aa1-9cea-099a61bde0c7.png">

**Comment by dzhlobo** [comment]
A couple of questions:
1. What options are allowed for "location" of schedule?
2. Do you have a global list of locations or should we perhaps make it a configurable list per Event?

**Comment by birs-math** [comment]
A PR #5 was submitted to resolve this issue (Location as a drop down #5).

**Comment by birs-math** [comment]
https://github.com/birs-math/workshops/pull/16

**Comment by birs-math** [comment]
This PR is passing both DEV and STAGING deployments.

**Comment by birs-math** [comment]
fix merged to PROD
