### ISSUE TITLE
Generate reports with workshop attendees’ special instructions

### ISSUE THREAD

**Issue by dzhlobo** [birs-math/workshops#7]
For every workshop we have members.
<img width="1734" alt="Screenshot 2023-01-13 at 12 10 39" src="https://user-images.githubusercontent.com/800337/212306752-df1d0163-0830-4d3b-8de7-63e4af0b98ce.png">

Sometimes it is needed to export information about attendees, including their "accomodation details". As I understand, currently an administrator has to go through each attendee, open attendee's page and copy information manually.

<img width="1734" alt="Screenshot 2023-01-13 at 12 12 55" src="https://user-images.githubusercontent.com/800337/212307258-896b0184-0f49-4f6e-bae8-46644f405abb.png">

We'd like to be able to export this information automatically.

**Comment by dzhlobo** [comment]
A few questions about this issue:
1. What kind of information is required in export? What is definitely not needed?
2. Would it be okay to export list of attendees as a CSV file?
3. Do we need to export every group or only particular ones (e.g. only "confirmed members")?

**Comment by birs-math** [comment]
BIRS team will provide a mock up in excel of expected attributes to the CSV

**Comment by birs-math** [comment]
This issue is closed. We merged PR to PROD for CSV report export. Thanks
